services:
  pig-hadoop:
    build: .
    container_name: pig-lab-engine
    volumes:
      - ./pig_scripts:/scripts
      - ./data:/data
    ports:
      - "50070:50070"
      - "8088:8088"
    stdin_open: true
    tty: true
    command: /bin/bash
